name: npm test

on:
  workflow_dispatch:

jobs:
  run-npm-install:

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        node: [20, lts]

        include:
          - os: ubuntu-latest
            node: 18

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: run install
        run: |
          npm install
          npm test